//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	json "encoding/json"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertAlert) DeepCopyInto(out *AlertAlert) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.SendOnResolved != nil {
		in, out := &in.SendOnResolved, &out.SendOnResolved
		*out = new(bool)
		**out = **in
	}
	if in.ProviderOverride != nil {
		in, out := &in.ProviderOverride, &out.ProviderOverride
		*out = make(map[string]json.RawMessage, len(*in))
		for key, val := range *in {
			var outVal []byte
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(json.RawMessage, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertAlert.
func (in *AlertAlert) DeepCopy() *AlertAlert {
	if in == nil {
		return nil
	}
	out := new(AlertAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientConfig) DeepCopyInto(out *ClientConfig) {
	*out = *in
	if in.OAuth2Config != nil {
		in, out := &in.OAuth2Config, &out.OAuth2Config
		*out = new(ClientOAuth2Config)
		(*in).DeepCopyInto(*out)
	}
	if in.IAPConfig != nil {
		in, out := &in.IAPConfig, &out.IAPConfig
		*out = new(ClientIAPConfig)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(ClientTLSConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientConfig.
func (in *ClientConfig) DeepCopy() *ClientConfig {
	if in == nil {
		return nil
	}
	out := new(ClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientIAPConfig) DeepCopyInto(out *ClientIAPConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientIAPConfig.
func (in *ClientIAPConfig) DeepCopy() *ClientIAPConfig {
	if in == nil {
		return nil
	}
	out := new(ClientIAPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientOAuth2Config) DeepCopyInto(out *ClientOAuth2Config) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientOAuth2Config.
func (in *ClientOAuth2Config) DeepCopy() *ClientOAuth2Config {
	if in == nil {
		return nil
	}
	out := new(ClientOAuth2Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientTLSConfig) DeepCopyInto(out *ClientTLSConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientTLSConfig.
func (in *ClientTLSConfig) DeepCopy() *ClientTLSConfig {
	if in == nil {
		return nil
	}
	out := new(ClientTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsConfig) DeepCopyInto(out *DnsConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsConfig.
func (in *DnsConfig) DeepCopy() *DnsConfig {
	if in == nil {
		return nil
	}
	out := new(DnsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointEndpoint) DeepCopyInto(out *EndpointEndpoint) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = make([]*AlertAlert, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(AlertAlert)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.DNSConfig != nil {
		in, out := &in.DNSConfig, &out.DNSConfig
		*out = new(DnsConfig)
		**out = **in
	}
	if in.SSHConfig != nil {
		in, out := &in.SSHConfig, &out.SSHConfig
		*out = new(SshConfig)
		**out = **in
	}
	if in.ClientConfig != nil {
		in, out := &in.ClientConfig, &out.ClientConfig
		*out = new(ClientConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.UIConfig != nil {
		in, out := &in.UIConfig, &out.UIConfig
		*out = new(UiConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointEndpoint.
func (in *EndpointEndpoint) DeepCopy() *EndpointEndpoint {
	if in == nil {
		return nil
	}
	out := new(EndpointEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Gatus) DeepCopyInto(out *Gatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Gatus.
func (in *Gatus) DeepCopy() *Gatus {
	if in == nil {
		return nil
	}
	out := new(Gatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Gatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusList) DeepCopyInto(out *GatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Gatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusList.
func (in *GatusList) DeepCopy() *GatusList {
	if in == nil {
		return nil
	}
	out := new(GatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusSpec) DeepCopyInto(out *GatusSpec) {
	*out = *in
	in.Endpoint.DeepCopyInto(&out.Endpoint)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusSpec.
func (in *GatusSpec) DeepCopy() *GatusSpec {
	if in == nil {
		return nil
	}
	out := new(GatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusStatus) DeepCopyInto(out *GatusStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusStatus.
func (in *GatusStatus) DeepCopy() *GatusStatus {
	if in == nil {
		return nil
	}
	out := new(GatusStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SshConfig) DeepCopyInto(out *SshConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SshConfig.
func (in *SshConfig) DeepCopy() *SshConfig {
	if in == nil {
		return nil
	}
	out := new(SshConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UiBadge) DeepCopyInto(out *UiBadge) {
	*out = *in
	if in.ResponseTime != nil {
		in, out := &in.ResponseTime, &out.ResponseTime
		*out = new(UiResponseTime)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UiBadge.
func (in *UiBadge) DeepCopy() *UiBadge {
	if in == nil {
		return nil
	}
	out := new(UiBadge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UiConfig) DeepCopyInto(out *UiConfig) {
	*out = *in
	if in.Badge != nil {
		in, out := &in.Badge, &out.Badge
		*out = new(UiBadge)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UiConfig.
func (in *UiConfig) DeepCopy() *UiConfig {
	if in == nil {
		return nil
	}
	out := new(UiConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UiResponseTime) DeepCopyInto(out *UiResponseTime) {
	*out = *in
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UiResponseTime.
func (in *UiResponseTime) DeepCopy() *UiResponseTime {
	if in == nil {
		return nil
	}
	out := new(UiResponseTime)
	in.DeepCopyInto(out)
	return out
}
